#!/bin/bash

case $1 in
	"-R")
		wal -R
		;;
	*)
		wal -i $1
		;;
esac

spicetify -q update
xdotool key Super+F5

source ~/.cache/wal/colors.sh

#openrgb -m static -c ${color12:1:6}
#python3 $HOME/bin/extra/OpenRGBPywal.py ${color12:1:6} ${color9:1:6}
