#!/bin/bash

dir=./set-theme-themes

case $1 in
"create")
	echo "What's the name for the new theme?"
	read theme
	touch $dir/$theme

	echo "What's the theme's wallpaper?"
	wallpaper=`zenity --file-selection`
	cp $wallpaper $dir/$theme.jpg

	echo "What's the theme's color? (Valid CSS color names only)"
	read color
	echo $color > $dir/$theme

	echo "what's the theme's hex color?"
	hex=$(zenity --color-selection --show-palette | python3 ./RGBtoHex.py)
	echo $hex >> $dir/$theme
	;;

"list")
	for file in $dir/*
	do
		theme=$(basename $file) 
		if [[ $theme != *jpg ]]; then 
			echo $theme
		fi
	done
	;;

*)
	if test -f $dir/$1; then
		sed -i "s/.*feh.*--bg-scale.*/feh --no-fehbg --bg-scale '"$dir"\\/"$1".jpg'/" $HOME/.fehbg
		feh --no-fehbg --bg-scale $dir/$1.jpg

		color=$(head -n 1 $dir/$1)
		sed -i "s/.*openrgb.*/openrgb -m static -c "$color"/" $HOME/.fehbg
		openrgb -m static -c $color

		hex=$(sed -n 2p $dir/$1)
		echo "s/static const char col_cyan[].*/static const char col_cyan[]        = \""$hex"\"\\;/" 
		sed -i "s/static const char col_cyan\\[\\].*/static const char col_cyan\\[\\]        = \""$hex"\"\\;/" $HOME/GitPrograms/dwm/config.h
		cd $HOME/GitPrograms/dwm/
		sudo make clean install
		cd $dir
		cd ..
		xdotool key "super+shift+q"
		
	else
		echo "INVALID COMMAND"
	fi
	;;
esac


